# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180421_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='end',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='fri',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='mon',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='start',
            field=models.TimeField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='thu',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='tue',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='wed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
